branch-defaults:
  master:
    environment: laravel-vue
environment-defaults:
  laravel-vue:
    branch: null
    repository: null
global:
  application_name: map-cicd
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
